config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'
  get 'home/about' => 'homes#about', as: 'about'
  devise_for :users
  resources :users, only: [:show,:index,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
  	get 'followers' => 'relationships#followers', as: 'followers'
  end
  resources :books, only: [:index, :show, :edit, :create, :destroy, :update] do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	has_many :favorites, dependent: :destroy
	has_many :post_comments, dependent: :destroy

	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}
	
    def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
    end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post_image
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  validates :comment, presence: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  attachment :profile_image, destroy: false

  validates :name, length: {maximum: 20, minimum: 2}, uniqueness: true
  validates :introduction, length: {maximum: 50}
  
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
  has_many :followings, through: :relationships, source: :followed
  
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!, except: [:top, :about]
	before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def after_sign_in_path_for(resource)
    user_path(resource)
  end 

  def after_sign_out_path_for(resource)
    root_path(resource)
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_action :authenticate_user!
	before_action :ensure_correct_user, only: [:edit, :update, :destroy]

  def show
    @book = Book.find(params[:id])
    @book_new = Book.new
    @post_comment = PostComment.new

  end

  def index
    @books = Book.all
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
  end



  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path, notice: "successfully delete book!"
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def ensure_correct_user
    @book = Book.find(params[:id])
    unless @book.user == current_user
      redirect_to books_path
    end
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!

  def create
    @book = Book.find(params[:book_id])
    favorite = @book.favorites.new(user_id: current_user.id)
    favorite.save
    redirect_to request.referer
  end

  def destroy
    @book = Book.find(params[:book_id])
    favorite = @book.favorites.find_by(user_id: current_user.id)
    favorite.destroy
    redirect_to request.referer
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @book = Book.find(params[:book_id])
    @post_comment = PostComment.new(post_comment_params)
    @post_comment.book_id = @book.id
    @post_comment.user_id = current_user.id
    if @post_comment.save
      redirect_to request.referer
    else
      render 'books/show'
    end
  end

	def destroy
		@book = Book.find(params[:book_id])
  	post_comment = @book.post_comments.find(params[:id])
		post_comment.destroy
		redirect_to request.referer
	end

	private
	def post_comment_params
		params.require(:post_comment).permit(:comment)
	end


end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :authenticate_user!
	def create
		current_user.follow(params[:user_id])
		redirect_to request.referer
	end

	def destroy
		current_user.unfollow(params[:user_id])
		redirect_to request.referer
	end
  def followings
		user = User.find(params[:user_id])
		@users = user.followings
  end

  def followers
		user = User.find(params[:user_id])
		@users = user.followers
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:edit, :update]

  def show
    @book = Book.new
    @user = User.find(params[:id])
    @books = @user.books
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render "edit"
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.erb
<%= form_with model:book, local:true do |f| %>
  <div class="field row">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'col-xs-12 book_title' %>
  </div>

  <div class="field row">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'col-xs-12 book_body' %>
  </div>

  <div class="actions row">
    <%= f.submit class: 'btn btn-primary col-xs-12' %>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= link_to user_path(book.user) do %>
          <%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %>
          <% end %>
        </td>
        <td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
        <td><%= book.body %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/edit.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3">

		<h1>Editing Book</h1>
		<% if @book.errors.any? %>
		  <div id="error_explanation">
        <h3><%= @book.errors.count %>error prohibited this obj from being saved:</h3>
        <ul>
          <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

		<%= render "books/form", book: @book %>
		<%= link_to "Show", book_path(@book), class: "book_#{@book.id}" %>
		<%= link_to "Back", books_path, class: "back" %>

	</div>
	<div class="col-md-3"></div>

</div>

app/views/books/index.html.erb
<div class="row">
	<% if @book.errors.any? %>
		<div id="error_explanation">
			<h3><%= @book.errors.count %>error prohibited this obj from being saved:</h3>
			<ul>
				<% @book.errors.full_messages.each do |message| %>
				<li><%= message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: current_user %>

		<h2>New book</h2>
		<%= render 'books/form', book: @book %>

	</div>

	<div class="col-xs-9">
		<h2>Books index</h2>
		<!--books一覧 -->
		<table class="table table-hover table-inverse">
			<thead>
				<tr>
					<th></th>
					<th>Title</th>
					<th>Opinion</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% @books.each do |book| %>
				<tr>
					<td>
						<%= link_to user_path(book.user) do %>
							<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
						<% end %>
					</td>
					<td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
					<td><%= book.body %></td>
				</tr>
				<% end %>
			</tbody>
		</table>

		<!--books一覧 -->


	</div>
</div>

app/views/books/show.html.erb
<div class='row'>
  <div class='col-xs-3'>
    <h2>User info</h2>
    <%= render 'users/info', user: @book.user %>
    <h2>New book</h2>
    <%= render 'form', book: Book.new %>
  </div>


  <div class='col-xs-9'>
		<h2>Book detail</h2>
		<table class='table'>
		  <tr>
        <td><%= link_to user_path(@book.user) do %>
          <%= attachment_image_tag(@book.user, :profile_image, :fill, 100, 100, fallback: "no-image-icon.jpg") %><br>
          <%= @book.user.name %>
          <% end %>
        </td>
        <td><%= link_to @book.title, book_path(@book) %></td>
        <td><%= @book.body %></td>
        <td class="favorite-btn"><%= render "favorites/favorite-btn", book: @book %></td>
        <td>コメント数: <%= @book.post_comments.count %></td>

        <% if @book.user == current_user %>
          <td><%= link_to 'Edit', edit_book_path(@book), class: "btn-sm btn-success edit_book_#{@book.id}" %></td>
          <td><%= link_to 'Destroy', book_path(@book), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn-sm btn-danger destroy_book_#{@book.id}"%></td>
        <% end %>
      </tr>
    </table>
    <table>
      <% @book.post_comments.each do |post_comment| %>
        <% post_comment_user = post_comment.user %>
        <tr>
        	<td>
        		<%= link_to user_path(post_comment_user), class: "user_#{post_comment_user.id}" do %>
          		<%= attachment_image_tag post_comment_user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg", size: "50x50" %><br>
          		<%= post_comment_user.name %>
        		<% end %>
        	</td>
        	<td><%= post_comment.comment %></td>
        	<% if current_user == post_comment_user %>
          	<td><%= link_to 'Destroy', book_post_comment_path(post_comment.book_id, post_comment.id), class: 'btn-sm btn-danger', method: :delete %></td>
        	<% end %>
        </tr>
      <% end %>
    </table>
    <%= form_with model:[@book,@post_comment], local: true do |f| %>
      <%= f.text_area :comment, size:"90x5" %>
      <%= f.submit '送信'%>
    <% end %>

  </div>
</div>

app/views/favorites/_favorite-btn.html.erb
<% if book.favorited_by?(current_user) %>
  <%= link_to book.favorites.count, book_favorites_path(book), method: :delete, class: "glyphicon glyphicon-heart" %>
<% else %>
  <%= link_to book.favorites.count, book_favorites_path(book), method: :post, class: "glyphicon glyphicon-heart-empty" %>
<% end %>

app/views/homes/about.html.erb
<h1>Welcome to <span class='glyphicon glyphicon-book'></span><strong>Bookers</strong>!</h1>

app/views/homes/top.html.erb
<div class="row">
  <div class='top-message col-xs-offset-3 col-xs-6'>
    <h1>welcome to <span class='glyphicon glyphicon-book'></span><strong>Bookers</strong>  !!</h1>
    <p>In  <span class='glyphicon glyphicon-book'></span><strong>Bookers</strong>, </p>
    <p>you can share and exchange  your opinions , inpressions , and emotions</p>
    <p> about various books!</p>

    <div class="btn-wrapper">
      <div class="row">
        <p><%= link_to 'Log in', new_user_session_path, class: "btn btn-info col-xs-10 col-xs-offset-1" %></p>
      </div>
      <div class="row">
        <p><%= link_to 'Sign Up', new_user_registration_path, class: "btn btn-success col-xs-10 col-xs-offset-1" %></p>
      </div>
    </div>

  </div>
</div>

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(obj.errors.count, "error") %> prohibited this obj from being saved:</h3>

    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class='container'>
  	<div class='row'>
    	<div class='col-xs-3 col-xs-offset-9'>
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav class='nav navbar-nav navbar-left' >
      <span>Bookers</span>
    </nav>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to ' Home', user_path(current_user), class: 'glyphicon glyphicon-home home' %></li>
          <li><%= link_to ' Users', users_path, class: 'glyphicon glyphicon-user users' %></li>
          <li><%= link_to ' Books', books_path, class: 'glyphicon glyphicon-book books'%></li>
          <li><%= link_to ' logout', destroy_user_session_path, method: :delete, class: 'glyphicon glyphicon-log-out logout' %></li>
        <% else %>
          <li><%= link_to ' Home', root_path, class: 'glyphicon glyphicon-home home' %></li>
          <li><%= link_to ' About', about_path, class: 'glyphicon glyphicon-link about' %></li>
          <li><%= link_to ' sign up', new_user_registration_path, class: 'glyphicon glyphicon-edit sign_up' %></li>
          <li><%= link_to ' login', new_user_session_path, class: 'glyphicon glyphicon-log-in sign_in'%></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2-debug</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>

    <div class="container">
      <p id="notice"><%= notice %></p>
        <%= yield %>
    </div>

    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/relationships/followers.html.erb
<h2>Follower Users</h2>
<% if @users.exists? %>
  <%= render '/users/index', users: @users %>
<% else %>
  <p>ユーザーはいません</p>
<% end %>

app/views/relationships/followings.html.erb
<h2>Follow Users</h2>
<% if @users.exists? %>
  <%= render '/users/index', users: @users %>
<% else %>
  <p>ユーザーはいません</p>
<% end %>

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  


  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user_path(user), class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
</table>

<div class='row'>
  <%= link_to '', edit_user_path(user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{user.id}" %>
</div>

app/views/users/_profile.html.erb
<table class="table">
	<tr><%= attachment_image_tag(@user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></tr>

	<tr>
		<th>name</th>
		<th><%= user.name %></th>
	</tr>

	<tr>
		<th>introduction</th>
		<th><%= user.introduction %></th>
	</tr>
</table>

<div class="row">
	<%= link_to '', edit_user_path(user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{user.id}" %>
</div>

app/views/users/edit.html.erb
<h2>User info</h2>

<%= form_with model:@user, local: true do |f| %>

	<!-- エラーメッセージ表示-->
	<% if @user.errors.any? %>
		<div id="error_explanation">
			<h3><%= @user.errors.count %>error prohibited this obj from being saved:</h3>
			<ul>
				<% @user.errors.full_messages.each do |message| %>
				<li><%= message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<!-- エラーメッセージ表示-->

	<div class="field">
		<%= f.label :name %>
		<%= f.text_field :name, class: "name" %>
	</div>

	<div class="field">
		<%= f.label :image %>
		<%= f.attachment_field :profile_image, class: "user_image" %>
	</div>

	<div class="field">
		<%= f.label :introduction %>
		<%= f.text_area :introduction, class: "introduction" %>
	</div>

	<div class="actions">
		<%= f.submit %>
	</div>

<% end %>

app/views/users/index.html.erb
<div class="row">
	<div class="col-xs-3">
    <h2>User info</h2>
      <%= render 'users/profile', user: current_user %>

    <h2>New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class="col-xs-9">
      <h2>Users</h2>
<!--users一覧 -->
      <table class="table">
	    <thead>
		    <tr>
			<th>image</th>
			<th>name</th>
			<th colspan="3"></th>
		</tr>
	</thead>

	<tbody>
		<% @users.each do |user| %>
		<tr>
			<td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
			<td><%= user.name %></td>
			<td><%= link_to "Show", user_path(user), class: "user_#{user.id}" %></td>
		</tr>
		<% end %>
	</tbody>
</table>
<!--users一覧 -->
  </div>
</div

app/views/users/show.html.erb
<div class="row">
	<div class="col-xs-3">
		<h2>User info</h2>
		<%= render 'users/profile', user: @user %>

		<h2>New book</h2>
		<%= render 'books/form', book: @book %>
	</div>
<div class="col-xs-9">
		<h2>Books</h2>
		<!--books一覧 -->
		<table class="table table-hover table-inverse">
			<thead>
				<tr>
					<th></th>
					<th>Title</th>
					<th>Opinion</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% @books.each do |book| %>
					<tr>
						<td>
							<%= link_to user_path(book.user) do %>
								<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
							<% end %>
						</td>
						<td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
						<td><%= book.body %></td>
					</tr>
				<% end %>
			</tbody>
		</table>
		<!--books一覧 -->
	</div>
</div>